### ISSUE TITLE
No thread synchronization

### ISSUE THREAD

**Issue by driverblock** [adafruit/Adafruit-Motor-HAT-Python-Library#15]
DualStepper example results in choppy movement. I believe this is because there is no thread synchronization in Adafruit_PWM_Servo_Driver.py
See https://forums.adafruit.com/viewtopic.php?f=50&t=104354

**Comment by caternuson** [comment]
This library is being deprecated. The new library is here:
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit
install instructions here:
https://learn.adafruit.com/adafruit-dc-and-stepper-motor-hat-for-raspberry-pi/installing-software
and the dual stepper example here:
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit/blob/master/examples/motorkit_dual_stepper_test.py

Please update to the new library and if this problem persists open a new issue in that repo.
