### ISSUE TITLE
Wrong indents in StepperTest.py

### ISSUE THREAD

**Issue by 14422** [adafruit/Adafruit-Motor-HAT-Python-Library#18]
The last two lines the the StepperTest.py have wrong indents and do not even compile. As they belong to a while loop as the other previous lines, they should have only 1 indent instead of 2. It's clearly visible even in GitHub.

```
   while (True):
    print("Single coil steps")
    myStepper.step(100, Adafruit_MotorHAT.FORWARD,  Adafruit_MotorHAT.SINGLE)
    myStepper.step(100, Adafruit_MotorHAT.BACKWARD, Adafruit_MotorHAT.SINGLE)

    print("Double coil steps")
    myStepper.step(100, Adafruit_MotorHAT.FORWARD,  Adafruit_MotorHAT.DOUBLE)
    myStepper.step(100, Adafruit_MotorHAT.BACKWARD, Adafruit_MotorHAT.DOUBLE)

    print("Interleaved coil steps")
    myStepper.step(100, Adafruit_MotorHAT.FORWARD,  Adafruit_MotorHAT.INTERLEAVE)
    myStepper.step(100, Adafruit_MotorHAT.BACKWARD, Adafruit_MotorHAT.INTERLEAVE)

    print("Microsteps")
        myStepper.step(100, Adafruit_MotorHAT.FORWARD,  Adafruit_MotorHAT.MICROSTEP)
        myStepper.step(100, Adafruit_MotorHAT.BACKWARD, Adafruit_MotorHAT.MICROSTEP)
```

In addition to that, has anyone even tried to run this code with a stepper motor? Can't seem to get it move my stepper motor smoothly (which is powered by an external power). Motor is zig-zagging back and forth even if there's just one forward command.

**Comment by tdicola** [comment]
Ah thanks for catching it, this should be fixed with the latest commit.  For the stepper issue make sure you have the coils connected correctly.  If you don't have a datasheet or info for the stepper check this out for details on determining the coils manually: http://www.jasonbabcock.com/computing/breadboard/unipolar/index.html
