### ISSUE TITLE
Android Things support

### ISSUE THREAD

**Issue by zugaldia** [adafruit/Adafruit-Motor-HAT-Python-Library#19]
Hey team, I've started porting this library to Android Things (Java). The [code is here](https://github.com/zugaldia/adafruit-motor-hat) and, though it only supports DC motors, it's already useful for projects:

[![image](https://cloud.githubusercontent.com/assets/6964/22185065/79e5f2f6-e0ac-11e6-8600-0a52cb6fe9fa.png)](https://www.youtube.com/watch?v=NBnw2-xwH00)

Feel free to close this ticket, I I just wanted to let you know about this port. Thanks for opensourcing this Python library :)

**Comment by ladyada** [comment]
neat!

**Comment by caternuson** [comment]
Closing since this was just a project share. But for anyone coming across this, be aware:
This library is being deprecated. Please update to using the new library here:
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit
