### ISSUE TITLE
Disable "sec per step" message

### ISSUE THREAD

**Issue by elead1** [adafruit/Adafruit-Motor-HAT-Python-Library#25]
The "x sec per step" message when moving a stepper motor should be a debug message, and off by default. If using a CLI, the message clutters the display.

**Adafruit_MotorHAT_Motors.py**

    class Adafruit_StepperMotor:

        ...

        def __init__(self, controller, num, steps=200, debug=False):

            ...

            self.debug = debug

        ...

        def step(self, steps, direction, stepstyle):

            ...

            if self.debug:

                print("{} sec per step".format(s_per_s))

    ...

**Comment by caternuson** [comment]
This library is being deprecated. Please update to using the new library here:
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit
If you continue to have this issue, please open a new issue in that repo.
