### ISSUE TITLE
DC Motor Control can't go all on

### ISSUE THREAD

**Issue by MZachmann** [adafruit/Adafruit-Motor-HAT-Python-Library#27]
Hi,

There's no way to turn a DC motor fully on or off because the max value should be 4095 (or 4096 special) and 255*16 isn't that. I guess I can just set the pin on so it's not a big deal.

**Comment by ladyada** [comment]
hiya, can you point out the line you're referring to, that way we can be sure we're discussing the same thing :)

**Comment by MZachmann** [comment]
Yeah, the setSpeed method takes 0...255 but that makes the maximum value 255 * 16 so a speed of 255 isn't full on. It was trivial to fix but I did have to notice it. See line 213: self.MC._pwm.setPWM(self.PWMpin, 0, speed*16). Note I'm using that one output to toggle a relay on/off so it mattered.

**Comment by ladyada** [comment]
we're actually about to replace this library completely...can you wait a few days? :)

**Comment by MZachmann** [comment]
Honestly, I'm good. It was easy to fix on my end. I just wanted to inform you folks. Take your time. 
If you see bottom of (https://medium.com/home-wireless/how-to-build-a-hot-plate-reflow-oven-ecdc23ec9da7) it's working great for me. Cool product.

**Comment by caternuson** [comment]
This library is being deprecated. Please update to using the new library here:
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit
If you continue to have this issue, please open a new issue in that repo.
