### ISSUE TITLE
Turning to slow

### ISSUE THREAD

**Issue by justcp213** [adafruit/Adafruit-Motor-HAT-Python-Library#3]
hi

ive got a stepper with a 1:900 Transmission, which needs a Supply of 6-15V and 150mA.

When i m driving the Motor, like the example shows, the driver is pulling around 800 mA and the voltage is getting high to 18V.... Additional to that, the Stepper turns very very very slow. I tried a lot of changes, but nothing worked. Any ideas ?

**Comment by tdicola** [comment]
If the stepper is pulling that much current over its normal expected value, and turning really slowly it kind of sounds like it might be getting 'stuck' and being unable to turn the transmission.  I don't have a lot of pointers but you might try following up in the forums at http://forums.adafruit.com/  There are a lot more folks with stepper motor experience that might be able to help, thanks!
